# Generated by Django 3.1.3 on 2021-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TeacherID',
            field=models.CharField(max_length=15, verbose_name='员工号'),
        ),
    ]
