# Generated by Django 3.1.3 on 2021-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210513_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgrade',
            name='studentNum',
            field=models.CharField(max_length=15, verbose_name='学号'),
        ),
    ]
